#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Dec 07, 2022 06:11:48 PM CST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import ExportDXF_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1(root)
    ExportDXF_support.init(root, top)
    root.mainloop()


w = None


def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel(root)
    top = Toplevel1(w)
    ExportDXF_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_Toplevel1():
    global w
    w.destroy()
    w = None


class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.', background=_bgcolor)
        self.style.configure('.', foreground=_fgcolor)
        self.style.configure('.', font="TkDefaultFont")
        self.style.map('.', background=[
                       ('selected', _compcolor), ('active', _ana2color)])

        self.File_INP = tk.StringVar()
        self.File_NODE = tk.StringVar()
        self.File_PIPE = tk.StringVar()

        self.Top_Left_Item = tk.StringVar()
        self.Top_Right_Item = tk.StringVar()
        self.Bottom_Left_Item = tk.StringVar()
        self.Bottom_Right_Item = tk.StringVar()

        self.Digits = tk.StringVar()

        top.geometry("600x450+738+434")
        # top.minsize(120, 1)
        # top.maxsize(2564, 1421)
        top.resizable(0,  0)
        top.title("DXF匯出工具")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.017, rely=0.044, height=31, width=150)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='ne')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {微軟正黑體} -size 14 -weight bold")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''INP檔案路徑''')

        self.Label1_1 = tk.Label(top)
        self.Label1_1.place(relx=0.017, rely=0.156, height=31, width=150)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(anchor='ne')
        self.Label1_1.configure(background="#d9d9d9")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font="-family {微軟正黑體} -size 14 -weight bold")
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''NODE檔案路徑''')

        self.Label1_2 = tk.Label(top)
        self.Label1_2.place(relx=0.017, rely=0.267, height=31, width=150)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(anchor='ne')
        self.Label1_2.configure(background="#d9d9d9")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(font="-family {微軟正黑體} -size 14 -weight bold")
        self.Label1_2.configure(foreground="#000000")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''PIPE檔案路徑''')

        self.txt_inp = tk.Entry(top)
        self.txt_inp.place(relx=0.283, rely=0.044, height=27, relwidth=0.573)
        self.txt_inp.configure(background="white")
        self.txt_inp.configure(disabledforeground="#a3a3a3")
        self.txt_inp.configure(font="-family {微軟正黑體} -size 12")
        self.txt_inp.configure(foreground="#000000")
        self.txt_inp.configure(highlightbackground="#d9d9d9")
        self.txt_inp.configure(highlightcolor="black")
        self.txt_inp.configure(insertbackground="black")
        self.txt_inp.configure(selectbackground="blue")
        self.txt_inp.configure(selectforeground="white")
        self.txt_inp.configure(textvariable=self.File_INP)

        self.txt_node = tk.Entry(top)
        self.txt_node.place(relx=0.283, rely=0.156, height=27, relwidth=0.573)
        self.txt_node.configure(background="white")
        self.txt_node.configure(disabledforeground="#a3a3a3")
        self.txt_node.configure(font="-family {微軟正黑體} -size 12")
        self.txt_node.configure(foreground="#000000")
        self.txt_node.configure(highlightbackground="#d9d9d9")
        self.txt_node.configure(highlightcolor="black")
        self.txt_node.configure(insertbackground="black")
        self.txt_node.configure(selectbackground="blue")
        self.txt_node.configure(selectforeground="white")
        self.txt_node.configure(textvariable=self.File_NODE)

        self.txt_pipe = tk.Entry(top)
        self.txt_pipe.place(relx=0.283, rely=0.267, height=27, relwidth=0.573)
        self.txt_pipe.configure(background="white")
        self.txt_pipe.configure(disabledforeground="#a3a3a3")
        self.txt_pipe.configure(font="-family {微軟正黑體} -size 12")
        self.txt_pipe.configure(foreground="#000000")
        self.txt_pipe.configure(highlightbackground="#d9d9d9")
        self.txt_pipe.configure(highlightcolor="black")
        self.txt_pipe.configure(insertbackground="black")
        self.txt_pipe.configure(selectbackground="blue")
        self.txt_pipe.configure(selectforeground="white")
        self.txt_pipe.configure(textvariable=self.File_PIPE)

        self.btn_inp = tk.Button(top)
        self.btn_inp.place(relx=0.867, rely=0.044, height=34, width=68)
        self.btn_inp.configure(activebackground="#ececec")
        self.btn_inp.configure(activeforeground="#000000")
        self.btn_inp.configure(background="#d9d9d9")
        self.btn_inp.configure(command=ExportDXF_support.chooseINP)
        self.btn_inp.configure(disabledforeground="#a3a3a3")
        self.btn_inp.configure(font="-family {微軟正黑體} -size 14 -weight bold")
        self.btn_inp.configure(foreground="#000000")
        self.btn_inp.configure(highlightbackground="#d9d9d9")
        self.btn_inp.configure(highlightcolor="black")
        self.btn_inp.configure(pady="0")
        self.btn_inp.configure(text='''選''')

        self.btn_node = tk.Button(top)
        self.btn_node.place(relx=0.867, rely=0.156, height=34, width=68)
        self.btn_node.configure(activebackground="#ececec")
        self.btn_node.configure(activeforeground="#000000")
        self.btn_node.configure(background="#d9d9d9")
        self.btn_node.configure(command=ExportDXF_support.chooseNode)
        self.btn_node.configure(disabledforeground="#a3a3a3")
        self.btn_node.configure(font="-family {微軟正黑體} -size 14 -weight bold")
        self.btn_node.configure(foreground="#000000")
        self.btn_node.configure(highlightbackground="#d9d9d9")
        self.btn_node.configure(highlightcolor="black")
        self.btn_node.configure(pady="0")
        self.btn_node.configure(text='''選''')

        self.btn_pipe = tk.Button(top)
        self.btn_pipe.place(relx=0.867, rely=0.267, height=34, width=68)
        self.btn_pipe.configure(activebackground="#ececec")
        self.btn_pipe.configure(activeforeground="#000000")
        self.btn_pipe.configure(background="#d9d9d9")
        self.btn_pipe.configure(command=ExportDXF_support.choosePIPE)
        self.btn_pipe.configure(disabledforeground="#a3a3a3")
        self.btn_pipe.configure(font="-family {微軟正黑體} -size 14 -weight bold")
        self.btn_pipe.configure(foreground="#000000")
        self.btn_pipe.configure(highlightbackground="#d9d9d9")
        self.btn_pipe.configure(highlightcolor="black")
        self.btn_pipe.configure(pady="0")
        self.btn_pipe.configure(text='''選''')

        self.Label1_2_1 = tk.Label(top)
        self.Label1_2_1.place(relx=0.067, rely=0.378, height=31, width=120)
        self.Label1_2_1.configure(activebackground="#f9f9f9")
        self.Label1_2_1.configure(activeforeground="black")
        self.Label1_2_1.configure(anchor='ne')
        self.Label1_2_1.configure(background="#d9d9d9")
        self.Label1_2_1.configure(disabledforeground="#a3a3a3")
        self.Label1_2_1.configure(font="-family {微軟正黑體} -size 14 -weight bold")
        self.Label1_2_1.configure(foreground="#000000")
        self.Label1_2_1.configure(highlightbackground="#d9d9d9")
        self.Label1_2_1.configure(highlightcolor="black")
        self.Label1_2_1.configure(text='''小數點位數''')

        self.Spinbox1 = tk.Spinbox(top, from_=1.0, to=5.0)
        self.Spinbox1.place(relx=0.283, rely=0.378,
                            relheight=0.067, relwidth=0.158)
        self.Spinbox1.configure(activebackground="#f9f9f9")
        self.Spinbox1.configure(background="white")
        self.Spinbox1.configure(buttonbackground="#d9d9d9")
        self.Spinbox1.configure(disabledforeground="#a3a3a3")
        self.Spinbox1.configure(font="-family {微軟正黑體} -size 12 -weight bold")
        self.Spinbox1.configure(foreground="black")
        self.Spinbox1.configure(highlightbackground="black")
        self.Spinbox1.configure(highlightcolor="black")
        self.Spinbox1.configure(insertbackground="black")
        self.Spinbox1.configure(selectbackground="blue")
        self.Spinbox1.configure(selectforeground="white")
        self.Spinbox1.configure(textvariable=self.Digits)

        self.Label1_2_1_1 = tk.Label(top)
        self.Label1_2_1_1.place(relx=0.05, rely=0.556, height=31, width=120)
        self.Label1_2_1_1.configure(activebackground="#f9f9f9")
        self.Label1_2_1_1.configure(activeforeground="black")
        self.Label1_2_1_1.configure(anchor='ne')
        self.Label1_2_1_1.configure(background="#d9d9d9")
        self.Label1_2_1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_2_1_1.configure(
            font="-family {微軟正黑體} -size 14 -weight bold")
        self.Label1_2_1_1.configure(foreground="#000000")
        self.Label1_2_1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_2_1_1.configure(highlightcolor="black")
        self.Label1_2_1_1.configure(text='''管線資訊''')

        self.combox_TopLeft = ttk.Combobox(top)
        self.combox_TopLeft.place(
            relx=0.283, rely=0.511, relheight=0.069, relwidth=0.272)
        self.combox_TopLeft.configure(
            font="-family {微軟正黑體} -size 12 -weight bold")
        self.combox_TopLeft.configure(takefocus="")
        self.combox_TopLeft.configure(textvariable=self.Top_Left_Item)

        self.combox_TopRight = ttk.Combobox(top)
        self.combox_TopRight.place(
            relx=0.633, rely=0.511, relheight=0.069, relwidth=0.272)
        self.combox_TopRight.configure(
            font="-family {微軟正黑體} -size 12 -weight bold")
        self.combox_TopRight.configure(takefocus="")
        self.combox_TopRight.configure(textvariable=self.Top_Right_Item)

        self.combox_BottomLeft = ttk.Combobox(top)
        self.combox_BottomLeft.place(
            relx=0.283, rely=0.622, relheight=0.069, relwidth=0.272)
        self.combox_BottomLeft.configure(
            font="-family {微軟正黑體} -size 12 -weight bold")
        self.combox_BottomLeft.configure(takefocus="")
        self.combox_BottomLeft.configure(textvariable=self.Bottom_Left_Item)

        self.combox_BottomRight = ttk.Combobox(top)
        self.combox_BottomRight.place(
            relx=0.633, rely=0.622, relheight=0.069, relwidth=0.272)
        self.combox_BottomRight.configure(
            font="-family {微軟正黑體} -size 12 -weight bold")
        self.combox_BottomRight.configure(takefocus="")
        self.combox_BottomRight.configure(textvariable=self.Bottom_Right_Item)

        self.Label1_2_1_2 = tk.Label(top)
        self.Label1_2_1_2.place(relx=0.567, rely=0.511, height=31, width=30)
        self.Label1_2_1_2.configure(activebackground="#f9f9f9")
        self.Label1_2_1_2.configure(activeforeground="black")
        self.Label1_2_1_2.configure(background="#d9d9d9")
        self.Label1_2_1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2_1_2.configure(
            font="-family {微軟正黑體} -size 14 -weight bold")
        self.Label1_2_1_2.configure(foreground="#000000")
        self.Label1_2_1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2_1_2.configure(highlightcolor="black")
        self.Label1_2_1_2.configure(text='''(''')

        self.Label1_2_1_2_1 = tk.Label(top)
        self.Label1_2_1_2_1.place(relx=0.933, rely=0.511, height=31, width=30)
        self.Label1_2_1_2_1.configure(activebackground="#f9f9f9")
        self.Label1_2_1_2_1.configure(activeforeground="black")
        self.Label1_2_1_2_1.configure(background="#d9d9d9")
        self.Label1_2_1_2_1.configure(disabledforeground="#a3a3a3")
        self.Label1_2_1_2_1.configure(
            font="-family {微軟正黑體} -size 14 -weight bold")
        self.Label1_2_1_2_1.configure(foreground="#000000")
        self.Label1_2_1_2_1.configure(highlightbackground="#d9d9d9")
        self.Label1_2_1_2_1.configure(highlightcolor="black")
        self.Label1_2_1_2_1.configure(text=''')''')

        self.Label1_2_1_2_2 = tk.Label(top)
        self.Label1_2_1_2_2.place(relx=0.567, rely=0.622, height=31, width=30)
        self.Label1_2_1_2_2.configure(activebackground="#f9f9f9")
        self.Label1_2_1_2_2.configure(activeforeground="black")
        self.Label1_2_1_2_2.configure(background="#d9d9d9")
        self.Label1_2_1_2_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2_1_2_2.configure(
            font="-family {微軟正黑體} -size 14 -weight bold")
        self.Label1_2_1_2_2.configure(foreground="#000000")
        self.Label1_2_1_2_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2_1_2_2.configure(highlightcolor="black")
        self.Label1_2_1_2_2.configure(text='''-''')

        self.btn_Export = tk.Button(top)
        self.btn_Export.place(relx=0.633, rely=0.8, height=44, width=168)
        self.btn_Export.configure(activebackground="#ececec")
        self.btn_Export.configure(activeforeground="#000000")
        self.btn_Export.configure(background="#d9d9d9")
        self.btn_Export.configure(command=ExportDXF_support.exportDXF)
        self.btn_Export.configure(disabledforeground="#a3a3a3")
        self.btn_Export.configure(font="-family {微軟正黑體} -size 14 -weight bold")
        self.btn_Export.configure(foreground="#000000")
        self.btn_Export.configure(highlightbackground="#d9d9d9")
        self.btn_Export.configure(highlightcolor="black")
        self.btn_Export.configure(pady="0")
        self.btn_Export.configure(text='''開始匯出''')

        self.btn_Load = tk.Button(top)
        self.btn_Load.place(relx=0.7, rely=0.378, height=44, width=168)
        self.btn_Load.configure(activebackground="#ececec")
        self.btn_Load.configure(activeforeground="#000000")
        self.btn_Load.configure(background="#d9d9d9")
        self.btn_Load.configure(command=ExportDXF_support.loadData)
        self.btn_Load.configure(disabledforeground="#a3a3a3")
        self.btn_Load.configure(font="-family {微軟正黑體} -size 14 -weight bold")
        self.btn_Load.configure(foreground="#000000")
        self.btn_Load.configure(highlightbackground="#d9d9d9")
        self.btn_Load.configure(highlightcolor="black")
        self.btn_Load.configure(pady="0")
        self.btn_Load.configure(text='''載入資料''')


if __name__ == '__main__':
    vp_start_gui()
